//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingCart.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCart
    {
        public int CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CartStatusID { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual tblCartStatu tblCartStatu { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
